import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { makePayment } from '../utils/razorpay'
import tw from "twin.macro";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Finite Loop CLub - NMAMIT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Link href="/api/auth/signin">
          <a>Sign In</a>
        </Link>
        <Link href="/api/auth/signout">
          <a>Sign Out</a>
        </Link >

      </nav>
      <PayButton onClick={makePayment}>
        Pay
      </PayButton>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

const PayButton = tw.button`
  bg-red-500
  hover:bg-red-700
  text-white
  font-bold
  py-2
  px-4
  border
  border-black
  rounded
`;